#define ENDER3
#define ENDER3_STOCK_FRAME
#define CUSTOM_PRINTER_NAME
#define USER_PRINTER_NAME "Bear 3D"
#define STOCK_HOTEND_THERMISTOR
#define STOCK_BED_THERMISTOR
#define SHOW_CUSTOM_BOOTSCREEN
#define LCD_LANGUAGE en
